# Generated by Django 5.0.6 on 2024-05-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='제작자 이름', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='영화 제목', max_length=300)),
                ('subtitle', models.CharField(help_text='영화 부제목', max_length=500, null=True)),
                ('genre', models.CharField(help_text='영화 장르', max_length=200)),
                ('runningTime', models.IntegerField(help_text='영화 러닝 타임, minute')),
                ('description', models.TextField(help_text='영화 줄거리 및 설명')),
                ('posterImg', models.URLField(help_text='포스터 이미지 URL', max_length=700)),
                ('release', models.DateField(help_text='개봉일')),
                ('director_id', models.ForeignKey(help_text='제작자 고유 아이디', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gridCRUD.director')),
            ],
        ),
    ]
