# Generated by Django 5.0.6 on 2024-05-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridCRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director_id',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(help_text='제작자', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gridCRUD.director'),
        ),
    ]
