# Generated by Django 5.0.6 on 2024-05-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridCRUD', '0003_alter_film_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='runningTime',
            field=models.IntegerField(help_text='영화 러닝 타임, minute', null=True),
        ),
    ]
